name: CrateKeys
author: Primus
api: [1.12.0, 2.0.0]
description: "---"
main: Primus\CrateKeys\Main
version: 1.0.0

permissions:
 cratekeys.*:
  default: true
  description: 'Permission for all features on CrateKeys'
  child:
   cratekeys.recieve:
    description: "Allow to recieve keys while mining"
    default: true
   cratekeys.use:
    description: "Allow to use Crate Keys"
    default: true
   cratekeys.chest.create:
    description: "Allow to create Chest Crate"
    default: true
    